version: '3.8'

services:
  eureka-server:
    build: ../fullstack-ss-eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - edge-network

  api-gateway:
    image: axeldamage/fullstack-ss-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_GATEWAY_ROUTES_0_URI=http://bff:8081
      - SPRING_CLOUD_GATEWAY_ROUTES_1_URI=http://pet-service:3001
      - SPRING_CLOUD_GATEWAY_ROUTES_2_URI=http://geo-service:3002
      - SPRING_CLOUD_GATEWAY_ROUTES_3_URI=http://match-service:3003
    restart: unless-stopped
    networks:
      - edge-network
    depends_on:
      - eureka-server
      - bff

  bff:
    image: axeldamage/fullstack-ss-bff:latest
    container_name: bff
    ports:
      - "8081:8081"
    environment:
      - PET_SERVICE_URL=http://pet-service:3001
      - GEO_SERVICE_URL=http://geo-service:3002
      - MATCH_SERVICE_URL=http://match-service:3003
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    networks:
      - edge-network

  frontend:
    image: axeldamage/fullstack-ss-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - edge-network

  pet-service:
    image: axeldamage/fullstack-ss-pet-service:latest
    container_name: pet-service
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - edge-network

  geo-service:
    image: axeldamage/fullstack-ss-geo-service:latest
    container_name: geo-service
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - edge-network

  match-service:
    image: axeldamage/fullstack-ss-match-service:latest
    container_name: match-service
    ports:
      - "3003:3003"
    restart: unless-stopped
    networks:
      - edge-network

networks:
  edge-network:
    driver: bridge